# ================================
# Environment Variable Setup in YAML
# Real sensitive values are stored securely (e.g., in environment, .env files, or secret managers)
# YAML file references these environment variables using $VARIABLE_NAME syntax
# ================================

# -------------------------------
# Step 1: Real Data (Usually stored in environment or secret file)
# This section is NOT usually part of the YAML itself in real applications
# Shown here just for illustration
# -------------------------------

USERNAME : admin            # real username value
PASSWORD : admin123         # real password value
CON_STRING : 192.168.10.3:8080  # real database or server connection string

# -------------------------------
# Step 2: YAML References to Environment Variables
# These values are not hardcoded — instead, they refer to the actual environment variables
# -------------------------------

username: $USERNAME         # value will be pulled from environment variable USERNAME
password: $PASSWORD         # value will be pulled from environment variable PASSWORD
con-string: $CON_STRING     # value will be pulled from environment variable CON_STRING
